# Generated by Django 3.1.1 on 2021-02-03 01:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='мастер')),
                ('photo', models.ImageField(blank=True, upload_to='masters_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128, unique=True, verbose_name='услуга')),
                ('service_description', models.TextField(blank=True, verbose_name='текст услуги')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('img_1', models.ImageField(blank=True, upload_to='services_img')),
                ('img_2', models.ImageField(blank=True, upload_to='services_img')),
                ('img_3', models.ImageField(blank=True, upload_to='services_img')),
                ('is_active', models.BooleanField(default=True, verbose_name='услуга активна')),
                ('masters_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.masters')),
            ],
        ),
        migrations.CreateModel(
            name='ActionsNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('published', models.DateField(default=datetime.datetime.now, verbose_name='опубликовано')),
                ('description', models.TextField(verbose_name='текст новости')),
                ('is_active', models.BooleanField(default=True, verbose_name='акция активна')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='скидка')),
                ('finished', models.DateField(blank=True, verbose_name='окончание скидки')),
                ('services_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.services')),
            ],
        ),
    ]
