# Generated by Django 3.1.1 on 2021-02-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_masters_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='master_specialization',
            field=models.CharField(blank=True, max_length=256, verbose_name='специализация'),
        ),
    ]
