# Generated by Django 3.1.1 on 2021-02-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_services_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsnews',
            name='discount',
            field=models.PositiveIntegerField(blank=True, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='actionsnews',
            name='services_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.services'),
        ),
    ]
