# Generated by Django 3.1.1 on 2021-02-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210204_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsnews',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='скидка'),
        ),
    ]
