# Generated by Django 3.1.1 on 2021-02-04 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210204_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionsnews',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='actionsnews',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='actionsnews',
            name='services_id',
        ),
        migrations.AddField(
            model_name='services',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='services',
            name='finished',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='окончание скидки'),
        ),
    ]
