# Generated by Django 3.1.1 on 2021-02-05 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210204_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='client_name',
            field=models.CharField(default='guest', max_length=64, verbose_name='имя клиента'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='date_field',
            field=models.DateField(default=datetime.datetime.now, help_text='выберите дату', verbose_name='дата услуги'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=89140000000, help_text='вводить в формате 8-XXX-XXX-XXXX', verbose_name='телефон клиента'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='service_choice',
            field=models.CharField(choices=[('M', 'Стрижка мужская'), ('F', 'Стрижка женская'), ('CH', 'Стрижка детская'), ('OK', 'Окрашивание волос'), ('TR', 'Лечение, биоинкрустация волос'), ('LAM', 'Ламинирование волос'), ('UKL', 'Укладка'), ('MUP', 'Перманентный макияж'), ('LASH', 'Наращивание ресниц')], default='M', help_text='выберите услугу', max_length=4),
        ),
        migrations.AddField(
            model_name='contacts',
            name='time_field',
            field=models.TimeField(blank=True, default='9:00', help_text='выберите время', verbose_name='время записи'),
        ),
    ]
