# Generated by Django 3.1.1 on 2021-02-07 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210205_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='client_name',
            field=models.CharField(default='guest', max_length=10, verbose_name='имя клиента'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date_field',
            field=models.DateField(default=datetime.datetime.now, verbose_name='дата услуги'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.PositiveBigIntegerField(verbose_name='телефон клиента'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='service_choice',
            field=models.CharField(choices=[('Стрижка мужская', 'Стрижка мужская'), ('Стрижка женская', 'Стрижка женская'), ('Стрижка детская', 'Стрижка детская'), ('Окрашивание волос', 'Окрашивание волос'), ('Лечение, биоинкрустация волос', 'Лечение, биоинкрустация волос'), ('Ламинирование волос', 'Ламинирование волос'), ('Укладка', 'Укладка'), ('Перманентный макияж', 'Перманентный макияж'), ('Наращивание ресниц', 'Наращивание ресниц')], default='Стрижка мужская', max_length=64),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='time_field',
            field=models.TimeField(verbose_name='время записи'),
        ),
    ]
