# Generated by Django 3.1.1 on 2021-02-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210207_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='masters_choice',
            field=models.CharField(choices=[('Оксана', 'Оксана'), ('Вера', 'Вера')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='service_choice',
            field=models.CharField(choices=[('Стрижка мужская', 'Стрижка мужская'), ('Стрижка женская', 'Стрижка женская'), ('Стрижка детская', 'Стрижка детская'), ('Окрашивание волос', 'Окрашивание волос'), ('Лечение, биоинкрустация волос', 'Лечение, биоинкрустация волос'), ('Ламинирование волос', 'Ламинирование волос'), ('Укладка', 'Укладка'), ('Перманентный макияж', 'Перманентный макияж'), ('Наращивание ресниц', 'Наращивание ресниц')], default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='time_field',
            field=models.CharField(choices=[('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], default=None, max_length=5, verbose_name='время записи'),
        ),
    ]
