# Generated by Django 3.1.1 on 2021-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210207_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='masters_choice',
            field=models.CharField(choices=[('Юлия', 'Юлия')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='телефон клиента'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='time_field',
            field=models.CharField(default=None, max_length=5, verbose_name='время записи'),
        ),
    ]
