# Generated by Django 3.1.1 on 2021-02-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210207_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='masters_choice',
            field=models.CharField(choices=[('Оксана', 'Оксана'), ('Вера', 'Вера'), ('Юлия', 'Юлия')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='time_field',
            field=models.CharField(default=None, max_length=10, verbose_name='время записи'),
        ),
    ]
