# Generated by Django 3.1.1 on 2021-02-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210208_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionsnews',
            options={'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='masters',
            options={'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='masters_choice',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
