# Generated by Django 3.1.1 on 2021-02-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210208_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, upload_to='portfolio')),
                ('img_2', models.ImageField(blank=True, upload_to='portfolio')),
                ('img_3', models.ImageField(blank=True, upload_to='portfolio')),
                ('is_active', models.BooleanField(default=True, verbose_name='портфолио активно')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.services')),
            ],
            options={
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
