# Generated by Django 3.1.1 on 2021-02-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='img_3',
        ),
    ]
