# Generated by Django 3.1.1 on 2021-02-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_portfolio_img_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='masters_id',
        ),
        migrations.AddField(
            model_name='masters',
            name='master_services',
            field=models.ManyToManyField(blank=True, to='mainapp.Services'),
        ),
    ]
