# Generated by Django 3.1.1 on 2021-02-09 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210209_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='masters_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.masters'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='service_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.services'),
        ),
    ]
