# Generated by Django 3.1.1 on 2021-02-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_masters_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:30', '13:30'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00')], max_length=32, verbose_name='часы работы')),
            ],
            options={
                'verbose_name_plural': 'Время работы',
            },
        ),
        migrations.CreateModel(
            name='WorkDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], max_length=1, verbose_name='день недели')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.ManyToManyField(to='mainapp.Time', verbose_name='время работы')),
            ],
            options={
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
    ]
