# Generated by Django 3.1.1 on 2021-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_time_workdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='date',
            field=models.DateField(blank=True, verbose_name='дата'),
        ),
    ]
