# Generated by Django 3.1.1 on 2021-02-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210214_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdays',
            name='date',
        ),
    ]
