# Generated by Django 3.1.1 on 2021-02-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_workdays_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='days',
            field=models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=1, verbose_name='день недели'),
        ),
    ]
