# Generated by Django 3.1.1 on 2021-02-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210214_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdays',
            name='date',
            field=models.DateField(default=None, verbose_name='дата'),
        ),
    ]
