# Generated by Django 3.1.1 on 2021-02-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_workdays_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdays',
            name='date',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date_field',
            field=models.DateField(verbose_name='дата услуги'),
        ),
    ]
