# Generated by Django 3.1.1 on 2021-02-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20210214_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='action',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.actionsnews', verbose_name='акция'),
        ),
    ]
