# Generated by Django 3.1.1 on 2021-02-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20210214_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='action',
        ),
    ]
