# Generated by Django 3.1.1 on 2021-02-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_remove_contacts_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='portfolio'),
        ),
    ]
