# Generated by Django 3.2.3 on 2021-08-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20210803_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtime',
            name='time',
        ),
        migrations.AddField(
            model_name='recordtime',
            name='work_days',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='mainapp.workdays'),
        ),
        migrations.AlterField(
            model_name='recordtime',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.masters'),
        ),
    ]
