# Generated by Django 3.2.3 on 2021-08-03 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20210803_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtime',
            name='time',
            field=models.CharField(default='10:00', max_length=64),
        ),
        migrations.AlterField(
            model_name='recordtime',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
